import { Geist, Geist_Mono } from "next/font/google";
import Script from 'next/script'
import "./globals.css";
import MovieCard from '@/app/components/MovieCard.jsx';
import Footer from '@/app/components/Footer.jsx';

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Flixx Movie App",
  description: "Generated by create next app",
};

export default function RootLayout({ children })
{

  return (
    <html lang="en">
      <head>
        <Script src="https://cdn.jsdelivr.net/npm/swiper@11/swiper-bundle.min.js" />
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-white flex flex-col min-h-screen`}
      >

        {/* Main Content */}
        <main className="flex-1">
          {children}
        </main>

        {/* Footer */}
        <Footer />
      </body>
    </html>
  );
}
